- insights_content_template_renderer/DoT.py
- insights_content_template_renderer/tests/request_data_example.json
- insights_content_template_renderer/tests/utils_test.py
DoT.py was not correctly rendering nested loops because the incremental of `sid` variable in the renderer was not correct. The change here makes `sid` nonlocal variable instead of passing it via parameter.
> Fix DoT.py rendering nested loops

- requirements.txt
update js2py version
closes CCXDEV-9438
> update js2py version

- deploy/clowdapp.yaml
- insights_content_template_renderer/endpoints.py
- insights_content_template_renderer/tests/test_metrics.py
- requirements.txt
Adding prometheus metrics to the fastapi.
> [CCXDEV-9345] Add metrics

- deploy/test.yaml
- docs/deployment.md
The documentation was wrong, the app name should be `ccx-data-pipeline`.
> Fix wrong documentation

- dashboards/grafana-dashboard-insights-content-template-renderer.configmap.yaml
Same dashboard as in [ccx-upgrades-data-eng!11](https://gitlab.cee.redhat.com/ccx/ccx-upgrades-data-eng/-/merge_requests/11) but using the template renderer service.
> [CCXDEV-9345] Add the Grafana dashboard

- Dockerfile
- config-dev.yml
- config.yml
- deploy/clowdapp.yaml
- deploy/test.yaml
Move uvicorn config to configmap so that we can adjust the logging using clowder params.
> [CCXDEV-10294] Move uvicorn config to configmap

- insights_content_template_renderer/DoT.py
- insights_content_template_renderer/tests/DoT_test.py
- insights_content_template_renderer/tests/utils_test.py
- insights_content_template_renderer/utils.py
1. Reverting https://github.com/RedHatInsights/insights-content-template-renderer/pull/31 because it broke the UI.
2. Reverting https://github.com/RedHatInsights/insights-content-template-renderer/pull/29 because it's a workaround, not a real fix.
> [CCXDEV-10294] Revert all changes because the UI was broken

- insights_content_template_renderer/DoT.py
- insights_content_template_renderer/tests/DoT_test.py
- insights_content_template_renderer/utils.py
- requirements.txt
Use upstream dotJS trying to see if https://github.com/lucemia/doT/issues/5 solves [CCXDEV-10314](https://issues.redhat.com/browse/CCXDEV-10314).
> [CCXDEV-10314] Use upstream dotJS

- dashboards/grafana-dashboard-insights-content-template-renderer.configmap.yaml
Use a fixed UID for the Grafana dashboard.
Part of #CCXDEV-10803
- Bug fix (non-breaking change which fixes an issue)
> [CCXDEV-10803][Grafana] Use a fixed UID

- insights_content_template_renderer/DoT.py
- insights_content_template_renderer/tests/DoT_test.py
- insights_content_template_renderer/utils.py
- requirements.txt
This reverts the changes from https://github.com/RedHatInsights/insights-content-template-renderer/pull/35. I'm reverting because it is better to test this with BDD before moving to production.
> Revert #35

- insights_content_template_renderer/DoT.py
- insights_content_template_renderer/tests/DoT_test.py
- insights_content_template_renderer/tests/utils_test.py
- insights_content_template_renderer/utils.py
- requirements.txt
Updating the dot-js library fixing [this issue](https://github.com/lucemia/doT/issues/5). Also, converting the raw string into a normal one so that the fix actually works.
> [CCXDEV-10314] Fix bug with if-else

- deploy/clowdapp.yaml
- insights_content_template_renderer/endpoints.py
- insights_content_template_renderer/logging_utils.py
- logging.yml
Same as https://gitlab.cee.redhat.com/ccx/ccx-upgrades-data-eng/-/merge_requests/57.
Part of #CCXDEV-11344
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
TBD.
> [CCXDEV-11344] Use a custom logger handler in the logging.yml file

- deploy/clowdapp.yaml
Add a parameter to enable and disable logging to cloudwatch + fix configmap name
> [CCXDEV-11344] Fix ephemeral deployment

- deploy/clowdapp.yaml
Just using parameters in order to set the memory and CPU requests and limits from app-interface, making it easier and faster to configure.
- Configuration update
CI.
> [CCXDEV-12115] Add limits and requests parameters

- build_deploy.sh
This patch prevent a potential credentials leak in the build process
> Prevent creds leak during build

- requirements.txt
Stage is broken so I'm reverting to a commit that was working before: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/102715
> [CCXDEV-12786] Revert to a commit that is working on stage

- pr_check.sh
Add relevant IQE tests for template renderer.
> [CCXDEV-11023] Add service log tests to PR check

- deploy/clowdapp.yaml
- insights_content_template_renderer/endpoints.py
- insights_content_template_renderer/logging_utils.py
- insights_content_template_renderer/sentry.py
- requirements.txt
Adding capability to sent alerts to glitchtip.
[CCXDEV-10828](https://issues.redhat.com/browse/CCXDEV-10828)
Tested locally and in ephemeral
> [CCXDEV-10828] Adding glitchtip configuration

- insights_content_template_renderer/__init__.py
- insights_content_template_renderer/tests/utils_test.py
- insights_content_template_renderer/utils.py
Patch for CVE-2024-28397 + UT
The file used in the UT does not contain sensitive information, and should be present in both BSD and Unix based OS.
> [CCXDEV-12971] Patch CVE-2024-28397

- Dockerfile
- pr_check.sh
- requirements.txt
Setuptools library update. Tested in ephemeral
> [CCXDEV-13113] Setuptools library update

- renovate.json
Add a Renovate config to create grouped update PRs instead of separate ones for each dependency.
> [CCXDEV-15184] Add custom Renovate config to group update PRs
